# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.CharField(max_length=32)),
                ('object', models.BigIntegerField(default=-1)),
            ],
            options={
                'db_table': 'RolePrivilege',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserRole',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.RemoveField(
            model_name='learningcontextstructure',
            name='child_context',
        ),
        migrations.RemoveField(
            model_name='learningcontextstructure',
            name='parent_context',
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
        migrations.RemoveField(
            model_name='role',
            name='rights',
        ),
        migrations.AddField(
            model_name='learningcontext',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.LearningContext'),
        ),
        migrations.AddField(
            model_name='result',
            name='settings',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default='{questions: [], testsettings: {}}'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='settings',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default="{response: '', bookmarked: false}"),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='Default', max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LearningContextStructure',
        ),
        migrations.AddField(
            model_name='userrole',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='db.LearningContext'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleprivilege',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='privileges', to='db.Role'),
        ),
    ]
