# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20171005_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollments',
            field=models.ManyToManyField(related_name='users', to='db.LearningContext'),
        ),
    ]
