# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_user_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecomputer',
            name='settings',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(blank=True, null=True),
        )
    ]
