# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20171005_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='role',
            field=models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollment', to='db.Role'),
            preserve_default=False,
        ),
    ]
