# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_enrollment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollments',
            field=models.ManyToManyField(related_name='users', through='db.Enrollment', to='db.LearningContext'),
        ),
    ]
