# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_user_enrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='learning_context',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
