# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20171005_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleprivilege',
            name='privilege',
            field=models.CharField(max_length=64),
        ),
    ]
