# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20171005_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrollments',
            field=models.ManyToManyField(related_name='enrollments', through='db.Enrollment', to='db.LearningContext'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
