# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_auto_20171010_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
