# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20171027_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('settings', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ExamSettings',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='exam',
            name='settings',
        ),
        migrations.AddField(
            model_name='examsettings',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings', to='db.Exam'),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
