# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20171106_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsettings',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='securityauditlog',
            name='url',
        ),
        migrations.AddField(
            model_name='exam',
            name='settings',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='identifier',
            field=models.BigIntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='ExamSettings',
        ),
    ]
