# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20171106_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=80, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('settings', jsoneditor.fields.postgres_jsonfield.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Proctor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProctorAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', jsoneditor.fields.postgres_jsonfield.JSONField(blank=True, null=True)),
                ('proctor', models.ForeignKey(db_column='proctor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.Proctor')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProctorAssociation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProctorExamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('request_password', models.TextField(blank=True, null=True)),
                ('certify_score', models.CharField(blank=True, max_length=5, null=True)),
                ('settings', jsoneditor.fields.postgres_jsonfield.JSONField(blank=True, null=True)),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.Exam')),
                ('proctor', models.ForeignKey(db_column='proctor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.Proctor')),
                ('result', models.ForeignKey(db_column='result_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.Result')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProctorExamRequest',
                'managed': True,
            },
        ),
    ]
