# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_proctor_proctorassociation_proctorexamrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distractor',
            name='question',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(db_column='role_id', related_name='user', to='db.Role'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='settings',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={'Audience': {'targetedContexts': []}, 'ExamAids': {'calculators': [], 'cueSheets': '', 'dictionaries': [], 'keepNotes': False, 'materials': [], 'openBookName': '', 'otherCalculator': '', 'personalNotes': '', 'restroomBreak': False, 'whitelistedSites': []}, 'ExamInfo': {'consentGroup': 'yes', 'dateRange': {'from': '', 'to': ''}, 'instructionsToOther': '', 'instructionsToSelf': '', 'instructionsToStudents': 'Some instructions to the students!', 'linkToExam': '', 'owner': '', 'returnURL': '', 'scoreReductionDate': None, 'timeLimit': None, 'type': 'online'}, 'Feedback': {'allowViewScore': False, 'duringExam': False, 'duringReview': False, 'scoreFeedback': [], 'scoreLessThanAboveFeedback': ''}, 'Notifications': {'beforeExamCloses': 0, 'beforeExamClosesSelect': 'Days', 'beforeExamOpens': 0, 'beforeExamOpensSelect': 'Days', 'customMessage': '', 'emailInExam': False, 'instructorNotifications': False, 'messageGroup': 'standard', 'studentReminders': False}, 'QuestionSequence': [], 'Questions': {'additional': ['go-back'], 'numQuestionsRandomlySelected': 0, 'presentationGroup': 'one', 'questionSets': [], 'receiveQuestionGroup': 'all'}, 'Review': {'allowDownload': False, 'allowReviewAnyComputer': True, 'allowReviewOfExam': False, 'allowReviewQuestionsMissed': True, 'allowReviewWithoutPassword': False, 'showCorrectAnswers': False, 'timeLimit': '', 'timeLimitIdentifier': '', 'whenGroup': 'any-time'}, 'Security': {'attempts': 1, 'audienceGroup': 'aud', 'password': '', 'privacy': False}, 'Sharing': {'targetedUsers': []}, 'Sites': {'targetedSites': []}}),
        ),
        migrations.AlterField(
            model_name='learningcontext',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='db.LearningContext'),
        ),
        migrations.AlterField(
            model_name='proctor',
            name='settings',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(blank=True, default={'fee': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='proctorassociation',
            name='proctor',
            field=models.ForeignKey(db_column='proctor_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated', to='db.Proctor'),
        ),
        migrations.DeleteModel(
            name='Distractor',
        ),
    ]
